version: "3.7"

services:
  db:
    container_name: project-slack_postgres
    image: postgres:12
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: project_slack
    volumes:
      - /var/lib/postgresql/data
    ports:
      - "5432:5432"
